main: me.bartjazdz.AdvSurvival.Main
name: AdvSurvival
version: 1.0
description: Advanced Survival Plugin
author: Bartosz Jazdzyk
commands:
   register:
      description: register to server
      usage: /<command>
      permission: AdvSurvival.Login
      permission-message: You have not permission to use this command!!!
   login:
      description: login to server
      usage: /<command>
      permission: AdvSurvival.Login
      permission-message: You have not permission to use this command!!!
   help:
      description: show avaiable commands
      usage: /help
      permission: AdvSurvival.help
      permission-message: You have not permission to use this command!!!
   spawn:
      description: teleport player to spawn location
      usage: /<command>
      permission: AdvSurvival.spawn
      permission-message: You have not permission to use this command!!!
   setspawn:
      description: set spawn location
      usage: /<command>
      permission: AdvSurvival.setspawn
      permission-message: You have not permission to use this command!!!
   sethome:
      description: set home location
      usage: /<command>
      permission: AdvSurvival.homes
      permission-message: You have not permission to use this command!!!
   home:
      description: teleport to home location
      usage: /<command>
      permission: AdvSurvival.homes
      permission-message: You have not permission to use this command!!!
   setcorner1:
      description: set first corner of spawn area
      usage: /<command>
      permission: AdvSurvival.corners
      permission-message: You have not permission to use this command!!!
   setcorner2:
      description: set second corner of spawn area
      usage: /<command>
      permission: AdvSurvival.corners
      permission-message: You have not permission to use this command!!!
permissions:
   AdvSurvival.Login:
      description: Allow to register and login to server
      default: true
   AdvSurvival.help:
      description: Allow to use command help
      default: true
   AdvSurvival.setspawn: 
      description: Allow to set spawn position
      default: op
   AdvSurvival.spawn:
      description: Allow to use spawn command
      default: true
   AdvSurvival.homes:
      description: Allow to use home and sethome commands
      default: true
   AdvSurvival.corners:
      description: Allow to set area of spawn protection
      default: op